### ISSUE TITLE
Undefined property: Grav\Plugin\DropCapsPlugin::$backend

### ISSUE THREAD

**Issue by jpfleury** [Sommerregen/grav-plugin-dropcaps#1]
My config: Grav v0.9.39, DropCaps v1.3.0

After installing DropCaps (`bin/gpm install dropcaps`), the home page of my website just displays errors:

![crikey _there_was_an_error _-_2015-08-28_21 35 57](https://cloud.githubusercontent.com/assets/687082/9559953/4995c55e-4dcd-11e5-857d-6d1e936cb13c.png)

**Comment by Sommerregen** [comment]
Oops, I missed one line... for the meantime between now and the next release, change [`dropcaps.php (L159)`](https://github.com/Sommerregen/grav-plugin-dropcaps/blob/master/dropcaps.php#L159) to

``` php
if (!$this->dropcaps) {
  // Initialize DropCaps class
  ....
```

Thanks!

**Comment by jpfleury** [comment]
OK, thanks a lot.
